// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgFwUACewwTAgosqX5vix1cN0dWC-52y8',
    appId: '1:788591527272:web:a7de0bbd0a5b5822ac02dd',
    messagingSenderId: '788591527272',
    projectId: 'arthub-70906',
    authDomain: 'arthub-70906.firebaseapp.com',
    storageBucket: 'arthub-70906.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABMv8exRb2QsuDTC3bqF3bo0Usz-cq1uQ',
    appId: '1:788591527272:android:6c61d8671f69aa70ac02dd',
    messagingSenderId: '788591527272',
    projectId: 'arthub-70906',
    storageBucket: 'arthub-70906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt69i4WhQ7VT683GPA9SXJhF6LE-MG4FQ',
    appId: '1:788591527272:ios:34fb1d9edfbbc780ac02dd',
    messagingSenderId: '788591527272',
    projectId: 'arthub-70906',
    storageBucket: 'arthub-70906.appspot.com',
    iosBundleId: 'com.example.arthub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt69i4WhQ7VT683GPA9SXJhF6LE-MG4FQ',
    appId: '1:788591527272:ios:ade4ac18591006f0ac02dd',
    messagingSenderId: '788591527272',
    projectId: 'arthub-70906',
    storageBucket: 'arthub-70906.appspot.com',
    iosBundleId: 'com.example.arthub.RunnerTests',
  );
}
